### PR TITLE
Use updated upload_pypi action

### PR DESCRIPTION
**Pull request by niksirbi**
See https://github.com/neuroinformatics-unit/movement/pull/108 for an explanation.

This PR needs to be merged before the next PyPI release.

### CODE REVIEW

**Comment by niksirbi** [comment]
@adamltyson I can't seem to be able to pinpoint the problem with the CI failures. CI passes with pinned `neuroinformatics-unit/actions/test@v2.0.0` but fails with `neuroinformatics-unit/actions/test@v2` (which defaults to the latest actions release). I suspect that `xvfb` has something to do with it, because it's one of the things [that changed between these releases](https://github.com/neuroinformatics-unit/actions/releases/tag/v2.2.0). I played with turning the `use-xvfb` flag on and off, without success. I also fail to reproduce the problem locally on Ubuntu. I vaguely recall you dealing with `xvfb` before on this repository. Any ideas?

**Comment by niksirbi** [comment]
Alright @adamltyson , I've managed to track down the problem.
And the culprit is.... my eternal nemesis - `cv2`.

The issue was with a specific `render` method, which calls `cv2.imshow`. That command cannot work in headless environments (without a `DISPLAY`), which was causing the tests to crash when the render method was being tested.

I circumvented this by adding an optional `display=True` parameter to the render method, which I set to `False` during tests. This solves the problem for now, but I'm open to suggestions for a more general solution. For example, we could try to automatically detect if the method is being called in a headless environment?

`use-xvfb` had nothing to do with this, so I've disabled it (which is the default) as not needed.

**Comment by adamltyson** [comment]
Your approach seems sensible. Those tests aren't really asserting that the plots are created properly anyway. You could add some logic to detect the number of displays and only disable the plots when running headless. This would make the tests slightly more useful, but only slightly. 

Any chance cv2 can be replaced? It's always a pain.

**Comment by niksirbi** [comment]
I think it wouldn't be too hard to replace `cv2` given that it's only used in these two `render` methods, and nowhere else. It would definitely simplify dependency management, installation etc. But that's more of a question for @ClementineDomine to decide. Can we use matplotlib for the live rendering of the environment?

But meanwhile, I think I'll merge this PR (if you approve), to unblock PyPI releases, and to plug the security vulnerability with the codecov token.

**Comment by adamltyson** [comment]
Looks good to me. Moving away from cv2 would probably help with installation for users too.

**Comment by niksirbi** [comment]
I open an issue for `cv2` #117

**Pull request merged**
